### ISSUE TITLE
Self update

### ISSUE THREAD

**Issue by corps** [getsentry/devenv#131]
Love devenv, it's been helpful.

Things are changing and fixes are coming in.  Since I installed devenv, several fixes have come out that would have saved me headaches, but I was unaware that a new version or fix had been pushed.

A mechanism for monitoring when updates are available and making it easy to execute an update would help me and other users keep up with fixes, and it would help me when debugging a fellow developer's issues.

**Comment by joshuarli** [comment]
There's now a `devenv update` command you can run to update the global devenv! One exception: if you're inside sentry, `devenv sync` updates the devenv installed in sentry's virtualenv.

If your global devenv is on an older version you won't have the update command and need to update with: `~/.local/share/sentry-devenv/venv/bin/pip install -U sentry-devenv`

I opted against autoupdating since I don't want everyone's devenv to potentially break at the same time.
